### ISSUE TITLE
Hashketball - Learn.co does not recognize the work done on Nitrous

### ISSUE THREAD

**Issue by talgoldfus** [learn-co-curriculum/advanced-hashes-hashketball#26]
While using Nitrous  to complete the advanced-hashes-hashketball lesson on Learn.co the learn webiste does not recognize that i ran the tests ,passed them and submitted the solution to GitHub.

**Comment by drewvollrath** [comment]
I am also having this issue! A solution would be great. I have also filed a Bug Report on learn.co as I wasn't sure where the best place to report it would be.

**Comment by AnnJohn** [comment]
hi @talgoldfus, yes filing a bug report is the best place to report this. This space if for specific issues related to the curriculum content. 

Sorry for the trouble that you're having, but because it's a technical issue with Nitrous, bug reports are best for this. If you hover over your profile pic in Learn, you'll see an option to file a report. Thanks.
