### ISSUE TITLE
Issue specific to prework-001 version of this lab

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/advanced-hashes-hashketball#28]
There are two learn-co-student versions of this lab:

https://github.com/learn-co-students/hashketball-001-prework-web

https://github.com/learn-co-students/advanced-hashes-hashketball-001-prework-web

At some point, not sure where (I think when a student forks on Nitrous), the version that the student is working on ends up being the first one and not the second one, and their lights do not end up working as the lab they are actually completing is not the lab that the lights correlate to. (This issue is somewhat confusing, let me know if you want to chat about it). Can we remove the first prework version from Github?

<img width="461" alt="screen shot 2016-03-31 at 4 14 55 pm" src="https://cloud.githubusercontent.com/assets/2243896/14189555/e7f00448-f75b-11e5-82d6-a32d5f4a877d.png">

**Comment by pletcher** [comment]
Yes -- it seems like it only shows up once in the curriculum. https://learn.co/curriculum/tracks/10415/lessons/10559

Do we just delete the GitHub repo? The spelunking involved here is a bit tricky (more likely, I'm just not used to the curriculum tool's quirks yet).

**Comment by DanielSeehausen** [comment]
(Learn specificity aside, I believe this issue has since been resolved, and can no longer occur. Thank you for bringing it to our attention!)

Hi there! This request sounds like an improvement to the Learn platform. Raising issues on GitHub should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface improvements. You can reach them at support@learn.co. Alternatively, if Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
