### ISSUE TITLE
Instructions a bit misleading

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/advanced-hashes-hashketball#39]
The instructions say `'The :players key points to a hash of players whose names (as strings) are the keys to a hash containing their stats'` in regards to creating the hash, however the hash in the solution is different to what this sentence describes. 

For example, this is what you would anticipate the hash to look like from the instructions:
```
:players => {
        "Alan Anderson" => {
          :number => "0",
          :shoe => 16,
          :points => 22,
          :rebounds => 12,
          :assists => 12,
          :steals => 3,
          :blocks => 1,
          :slam_dunks => 1
        },
```

And this is what the solution looks like:
```
players: [
        {
          player_name: "Alan Anderson",
          number: 0,
          shoe: 16,
          points: 22,
          rebounds: 12,
          assists: 12,
          steals: 3,
          blocks: 1,
          slam_dunks: 1
        }, {
```

**Comment by sgharms** [comment]
Hey @FreeBreadsticks , I think we covered these concerns in these changes [here](https://github.com/learn-co-curriculum/advanced-hashes-hashketball/compare/6252d99a8bf12e3f94147c786f708a50038761d0...master). If you have any feedback on whether or not we helped, let us know. Otherwise, thanks for your input!
