### ISSUE TITLE
#big_shoe_rebound can return a false positive on testing

### ISSUE THREAD

**Issue by dahby** [learn-co-curriculum/advanced-hashes-hashketball#41]
Big shoe rebounds has only one test which can be easily gamed to pass.

`  describe '#big_shoe_rebounds' do

    it 'returns the number of rebounds of the player with the biggest shoe size' do
      expect(big_shoe_rebounds).to eq(12)
    end

  end`

The expected value of 12 relates to many of the players rebound stat, including the last player in the hash. As such, a method written as:
` 

    team_data[:players].each do |players, stats|

      if stats[:shoe] > 0 

        shoe_size = stats[:shoe]

        rebounds = stats[:rebounds]

      end

    end

 `

will pass because the last players rebounds just happen to coincide with the largest shoe size rebounds.

**Comment by maxwellbenton** [comment]
Hi @dahby,

Thanks for opening this ticket and providing feedback. We've updated the stats in this lab's instructions, tests, and solution so that there is only one player with the correct number of rebounds, which should false positives like the example you provided. Students forking this lab going forward should see the updated content.

If you do not believe that this issue has been addressed, please re-open this issue. Thank you for contributing to a Learn.co lesson! 💙
