### ISSUE TITLE
"Bismak" should be "Bismack"

### ISSUE THREAD

**Issue by darrendaz** [learn-co-curriculum/advanced-hashes-hashketball#43]
In the lesson data table "Bismak Biyombo" is misspelled. Being an NBA fan, I know for a fact that his name is spelled "Bismack Biyombo" and spelled it that way in my hash by memory.
This error probably should have been caught in the first test where you set up your hash definition, but I was on the second test of the lesson and spent almost 3 hours wondering why I kept receiving an error at his name in my method.

**Comment by fbohz** [comment]
I had this problem too. The RSPEC still has Bismak Biyombo but the instructions now have Bismack Biyombo.

**Comment by Bundo101** [comment]
yup you get an incorrect result for the super bonus question unless you correct this

**Comment by maxwellbenton** [comment]
Hello @darrendaz, 

Thank you for spotting this issue and opening this ticket to provide feedback. The content has been updated to contain the correct spelling of the player's name. 

Hello @fbohz and @Bundo101,

Thank you for your feedback as well! Due to an error, your student batch had not received the most recent updates, causing you to receive an updated readme with outdated test content. Sorry for the inconvenience! This has been fixed for all students in this online-prework going forward.

Thanks for contributing to a learn.co lesson!
