### ISSUE TITLE
Change back to a more sensible data structure

### ISSUE THREAD

**Issue by alexgriff** [learn-co-curriculum/advanced-hashes-hashketball#44]
In this commit the `game_hash` structure was changed: https://github.com/learn-co-curriculum/advanced-hashes-hashketball/commit/730f21111f46bf7c07839753a0a5fdf36dbd3b22

```ruby
# current instructions data structure
{
  home: {
    players: {
      "Player 1 Name" => {...},
      "Player 2 Name" => {...}
    }, 
    ...
}
```

Im pretty sure that this was a change that one specific instructor wanted to make at the time; that instructor is no longer here.

Not only do the Immersive Lecture Notes follow a different data structure (we have to do some hand-waving about the difference) https://github.com/flatiron-school/education-team-wiki/blob/update-mod-three-schedule/software-engineering/lessons/ruby/ruby-hashketball-review.md as the players array opens up some space for us to talk about enumerable methods, but

```ruby
# proposed change
{
  home: {
    players: [{}, {}, ...]
    ...
}
```
I really think the data structure above is a lot more sensible in terms of what a response from a JSON API might look like. I can't imagine a JSON API returning back a result where individual player names are keys.

For example, the github api doesnt return an object where my repo names are keys, but an array of repo objects https://api.github.com/users/alexgriff/repos

@maxwellbenton If this lab or something like it stays in the prework, I'd strongly advocate for a more realistic (and pedagogically helpful) data structure to reduce friction on Day 1

**Comment by sgharms** [comment]
Conceptually I have no resistance with what you propose.

Case 1

I agree, an Array of Hashes as you propose looks a lot more like what an API would return.

Case 2: 

But I also recognize that the basic proposition of a `dict` or a `Hash` is: "Something uniquey that we use to point to (potentially) something nested." And I also recognize that learners need some time to warm up to that idea.

I think the question is what muscle we're trying to target at this item's delivery. Is this so early that lack of API similarity makes it worth dropping; OR, have they experienced Hash enough that they should have it clear enough to start moving to something closer to reality?

Where it falls in Mod 1 is right on the tail of "we just taught you Hash." This makes me think no change (but be explicit that this challenge is trying to cater to the "Case 2" setup described above).


Regardless, I'm going to delay action on this until we begin our Mod1/2 rewrite (beginning presently).

**Comment by sgharms** [comment]
@alexgriff Did https://github.com/learn-co-curriculum/advanced-hashes-hashketball/compare/6252d99a8bf12e3f94147c786f708a50038761d0...master cover this concern? If so, please let me know so we can close.

**Comment by alexgriff** [comment]
@sgharms doesn't seem like it. This still remains:
` The `:players` key points to a hash of players whose names (as strings) are
  the keys to a hash containing their stats`

The suggested change key is that: "the `players` key points to an *array of hashes* where each has represents the stats of one particular player"

There's (imo) still many pedagogical advantages to the suggested change, starting with the lecture notes, what new hire teachers would begin looking at, using the suggested data structure; sets you up for teaching OO, each hash represents all the data for one player including the name. Thats also the structure this lab used to have & I know that we changed to the current data structure based on the whims of one person who no longer works here

**Comment by sgharms** [comment]
@alexgriff 

I think I figured the confusion out

1. The [lecture notes](https://github.com/flatiron-school/education-team-wiki/blob/update-mod-three-schedule/software-engineering/lessons/ruby/ruby-hashketball-review.md) use the "player name as key" `Hash`. You _don't_ believe this to be the correct ("I really think the data structure above [Array of Hashes] is a lot more sensible in terms..")

***AGREED*** change should be to update the lecture notes to use the "more sensible" structure.

2. So then the goal would be to have _this_ repo honor the same "more sensible" structure. Fully agree there as well. The solution b278e95 uses the "more sensible" structure. Please confirm.

3. And here's what I was missing, but that you caught: the README points to the non-sensible structure:

> The `:players` key points to a hash of players whose names (as strings) are the keys to a hash containing their stats.

Should be...

> The `:players` key points to a `Array` of `Hash`es. Each `Hash` contains their stats as listed below:

(add `player_name` as a key as attested by https://github.com/learn-co-curriculum/advanced-hashes-hashketball/blob/solution/hashketball.rb#L120-L131)

@maxwellbenton can you implement the fixes here and also work with Rob to make sure that the structure used in the lecture notes is the same one in `solution`?

**Comment by maxwellbenton** [comment]
Hi @alexgriff and @sgharms,

I've updated the instructions so that they reflect the data structure now in the solution:

> The `:players` key points to an `Array` of `Hash`es. Each `Hash` in the array should contain the players' stats as listed below and their stats can be found in the table below. The stats keys should be formatted like this:

and cleaned up the solution a bit. Will also review the lecture notes and open a PR to make sure it is aligned as there should no longer be a need to show students the two different data structures.

Closing this for now, but please reopen if there is anything that I may have missed in updating the instructions.

**Comment by justinamaple** [comment]
So I just went through this lab and found the new wording to be way more misleading then the old. 
By setting up :players as an Array of Hashes, you leave out the name entirely since each element in :players does not contain the name nor does the key. (According to the code snippet return for player_stats)

After spending a lot of time creating a separate lookup to associate player name with their prospective number and team (since some numbers are not unique between teams), I finally decided to just redo the structure, since the unit tests don't actually check the data structure of :players.

What made the most sense to me was a Hash of Hashes, this allows the user to search by using the name as a key, making the code much less convoluted.  Now that I see this is the original wording, I am puzzled about why it was changed. 

The first two searches, num_points_scored and shoe_size, require you to search by player name. In it's current state if I wanted to add it as a value to stats, I would have to remember to remove it when calling player_stats. (The code snippet with the return for this call is very misleading if this is the case)

**Comment by maxwellbenton** [comment]
Hi @justinamaple,

Thank you for your feedback. While I agree that if you or I were designing a nested data structure for our own use, it might make sense to use a hash of players - as you said, there are advantages like instant lookup that help with searching. However, the goal of this lab is to practice working with nested data, not to build the most ideal structure for this use case.

This data structure was chosen because it more closely mirrors common structures we see when working with remote data from JSON APIs. Often data from remote sources is put
together by a server at the time of the request in a variety of arrangements, entirely out of our control, and it is up to us to build the code that lets us traverse through it.

The current design is also good practice as you move towards object-oriented class relationships in Ruby. In this section, you will need to search through an indeterminate number of records using iteration and filtering.

Hope this helps!
