### ISSUE TITLE
#player_with_longest_name method test can't be passed

### ISSUE THREAD

**Issue by Seanhetzel** [learn-co-curriculum/advanced-hashes-hashketball#45]
The `#player_with_longest_name` method should return the player who has the longest name but: 

"Brendan Haywood" 
and 
"Bismack Biyombo"

 both have equally the longest names with 15 characters in length. 

Maybe there should be one name that is definitively the longest. Or am I misunderstanding what qualifies as the longest name?

**Comment by kargok** [comment]
I echo your sentiment, Sean!

Can someone provide further clarification?

**Comment by maxwellbenton** [comment]
Hi @Seanhetzel and @kargok,

Thank you for spotting this and providing feedback. Due to a previous typo fix in a player name, this test was no longer correctly passing. We've updated the readme, tests and solution with a different player name to ensure these bonus challenges are working properly for students in the future.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
